server:
  port: 9093

spring:
  application:
    name: tripplanner
  mvc:
    servlet:
      path: /tripplanner
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

google:
  client-id: ${GOOGLE_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# Outbound via Gateway  ⬇︎ keep ONLY ONE of each
triphub:
  base-url: ${TRIPHUB_BASE_URL:https://triphub}
tripprofile:
  base-path: ${TRIPPROFILE_BASE_PATH:/tripprofile}

