server:
  port: 9093


spring:
  application:
    name: tripplanner
  mvc:
    servlet:
      path: /tripplanner
  datasource:
    datasource:
      url: jdbc:h2:mem:tripplanner;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


logging:
  level:
    org.hibernate.tool.schema: info